kind: Reaction
apiVersion: v1
name: seeker-mcp
spec:
  kind: MCP
  queries:
    idle-players: |
      description: "Position alert for players who have been idle for more than 5 seconds"
      added:
        template: |
          {
            "description": "Player {{after.id}} was idle at position ({{after.x}}, {{after.y}})"
          }
    fast-players: |
      description: "Position alert for players who have moved more than once in the last second"
      added:
        template: |
          {
            "description": "Player {{after.id}} was moving fast to position ({{after.x}}, {{after.y}})"
          }
      updated:
        template: |
          {
            "description": "Player {{after.id}} was moving fast to position ({{after.x}}, {{after.y}}) from ({{before.x}}, {{before.y}})"
          }
      deleted:
        template: |
          {
            "description": "Player {{before.id}} is no longer at position ({{before.x}}, {{before.y}})"
          }
---
