apiVersion: v1
kind: Source
name: game
spec:
  kind: PostgreSQL  
  properties:
    host: host.docker.internal
    port: 5432
    user: postgres
    password: test
    database: game
    ssl: true
    tables:
      - public.player
