apiVersion: v1
kind: ContinuousQuery
name: idle-players
spec:
  mode: query
  sources:
    subscriptions:
      - id: game
  query: >
    MATCH
      (p:player { type: 'human' })
    WHERE drasi.trueLater(drasi.changeDateTime(p) <= (datetime.realtime() - duration( { seconds: 3 } )), drasi.changeDateTime(p) + duration( { seconds: 3 } ))

    RETURN
      p.id,
      p.x,
      p.y

---

apiVersion: v1
kind: ContinuousQuery
name: fast-players
spec:
  mode: query
  sources:
    subscriptions:
      - id: game
  query: >
    MATCH
      (p:player { type: 'human' })
    WHERE drasi.changeDateTime(p).epochMillis - drasi.previousValue(drasi.changeDateTime(p).epochMillis) < 1000

    RETURN
      p.id,
      p.x,
      p.y

---
apiVersion: v1
kind: ContinuousQuery
name: all-positions
spec:
  mode: query
  sources:
    subscriptions:
      - id: game
  query: >
    MATCH
      (p:player)
    RETURN
      p.id,
      p.x,
      p.y,
      p.type