apiVersion: v1
kind: ContinuousQuery
name: pdv
spec:
  mode: query
  sources:    
    subscriptions:
      - id: game
  query: > 
    MATCH 
      (p:player)
    RETURN
      p.id,
      p.x,
      p.y